### ISSUE TITLE
Retro Achievement Log-In doesn´t work

### ISSUE THREAD

**Issue by Macalanias** [TapiocaFox/Daijishou#524]
i logged in once succesfully. now after days the Retro Achievement widget says i have to log-in. username and password are correct, it doesn´t log-in, no matter what how often i save this things or how often i refresh the RA widget, or how often i restart the device (retroid pocket 3+)
i have the newest app version

retroarch´s Retro Achievement log-in works and recognices achievements

**Comment by Jetup13** [comment]
[RAWeb](https://github.com/RetroAchievements/RAWeb) will most likely need to be updated as there was a major update recently. This will most likely need to fixed in an app update. 

To explain why Retroachievements is working correctly on RetroArch is because it doesn't use RAWeb. Instead it uses [rcheevos](https://github.com/RetroAchievements/rcheevos). RAWeb is used to gather information on the website. While rcheevos is used for actually earning achievements and stuff like that.

**Comment by UrDone4** [comment]
I am also seeing this issue. When I reboot my device, the widget will show me logged in and I can browse my achievements as they were after the last time it synced. However, when it tries to sync to update, the widget then changes to "Please login"

**Comment by twopiearr** [comment]
I am also seeing this issue. Still seeing it after the update that brings RAW up to 4.0.

**Comment by cannnAvar** [comment]
Make sure you updated right. I know it sounds like "It's works on my device" answer. But google play don't get last update immediately.

**Comment by cannnAvar** [comment]
@Jetup13 i think we should close this

**Comment by Jetup13** [comment]
Yup, its been fixed with updated Daijisho builds
